# These are supported funding model platforms
# CodeMaster-AI Funding Configuration
# Supporting the development of enterprise-grade AI coding assistant

github: sharfuddin1 # Your GitHub username for GitHub Sponsors
patreon: # codemaster-ai (if you create one)
open_collective: # codemaster-ai (professional option for enterprises)
ko_fi: sharfuddin_ahmed # Easy one-time donations
tidelift: # For enterprise security and maintenance guarantees
community_bridge: # Open source community funding
liberapay: sharfuddin # European-friendly donation platform
issuehunt: sharfuddin1 # Bug bounty and feature funding
lfx_crowdfunding: # Linux Foundation project funding
custom: ['https://www.buymeacoffee.com/sharfuddin', 'https://paypal.me/sharfuddin'] # Direct payment options
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
